#!/usr/bin/env python3
from PyPDF2 import PdfFileReader, PdfFileMerger, PdfFileWriter
import yaml
import sys

dif = 0

# TODO _,args, , , = sys.argv
if len(sys.argv) > 3:
    dif = int(sys.argv[3])

with open(f"{sys.argv[2]}", "r") as stream:
    try:
        index = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

def indexer(yaml_index, merger, parent=None):
    for label in yaml_index.keys():
        if type(yaml_index[label]) == int:
            page = yaml_index[label]-1+dif
            merger.addBookmark(label, page, parent)
        else:
            page = yaml_index[label][0]-1+dif
            merger.addBookmark(label, page, parent)
            for dict_sublabel in yaml_index[label]:
                if type(dict_sublabel) == dict:
                    indexer(dict_sublabel, merger, parent=label)



if __name__ == '__main__':
    file_in = open(f'{sys.argv[1]}', 'rb')
    file_out = open(f'{sys.argv[1].split(".")[0]}_indexed.pdf', 'wb')

    pdf_reader = PdfFileReader(file_in)
    pdf_merger = PdfFileMerger()
    pdf_writer = PdfFileWriter()

    metadata = pdf_reader.getDocumentInfo()

    #  pdf_writer.cloneReaderDocumentRoot(pdf_reader)
    pdf_merger.append(file_in, import_bookmarks=False)
    pdf_merger.addMetadata(metadata)
    indexer(index, pdf_merger)
    pdf_merger.write(file_out)

    file_in.close()
    file_out.close()
